seedlibrary/urls.py
from django.conf.urls import patterns, include, url

from seedlibrary import views, views_search

urlpatterns = patterns('',
	url(r'^$', 'seedlibrary.views.home', name='home'),
	url(r'^seeds/create/$', 'seedlibrary.views.seed_create'),
	url(r'^seeds/create-confirm/$', 'seedlibrary.views.seed_create_confirm'),
	url(r'^seeds/$', 'seedlibrary.views.seeds'),
	url(r'^seeds/export/$', 'seedlibrary.views.seed_export'),
	url(r'^seeds/edit/(?P<id>[0-9]+)$', 'seedlibrary.views.seed_edit'),
	url(r'^seeds/confirm-archive/(?P<id>[0-9]+)$', 'seedlibrary.views.seed_confirm_archive'),
	url(r'^search/$', 'seedlibrary.views_search.seed_search'),
	url(r'^events/$', 'seedlibrary.views.events'),
	url(r'^seeds-at-event/(?P<id>[0-9]+)$', 'seedlibrary.views.seeds_at_event')
)

seednetwork/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from seednetwork import settings
from seednetwork.forms import SeedNetworkAuthForm, SeedNetworkPasswordChangeForm

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'seednetwork.views.home', name='home'),
    url(r'^seedlibrary/', include('seedlibrary.urls')),

    url(r'^$', 'seednetwork.views.home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # user management
	(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name':'login.html', 'authentication_form':SeedNetworkAuthForm}),
	(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name':'logout.html', 'next_page':'/'}),
	(r'^accounts/profile/$', 'seednetwork.views_user.profile'),
	(r'^accounts/member/(?P<mid>[0-9]+)$', 'seednetwork.views_user.member'),
	(r'^accounts/members/$', 'seednetwork.views_user.members'),

	(r'^accounts/profile-edit/$', 'seednetwork.views_user.edit_profile'),

    (r'^accounts/new-user/$', 'seednetwork.views_user.new_user'),


	(r'^accounts/reset-password/$', 'django.contrib.auth.views.password_reset',
		 {'template_name':'password_reset.html',
		  'email_template_name':'password_reset_email.html'}),

	(r'^accounts/reset-password/done/$', 'django.contrib.auth.views.password_reset_done',
		 {'template_name':'password_reset_done.html'}),

	(r'^accounts/reset-password-confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
	 'django.contrib.auth.views.password_reset_confirm', {'template_name':'password_reset_confirm.html'}),

	(r'^accounts/reset-password-complete/$', 'django.contrib.auth.views.password_reset_complete',
		{'template_name':'password_reset_complete.html'}),

	(r'^accounts/change-password/$', 'django.contrib.auth.views.password_change',
		 {'template_name':'password_change.html', 'password_change_form':SeedNetworkPasswordChangeForm}),

	(r'^accounts/change-password/done/$', 'django.contrib.auth.views.password_change_done',
		 {'template_name':'password_change_done.html'}),
)

if not settings.DEBUG:
	urlpatterns += patterns('',
		(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
	                        )

seedlibrary/models.py
from django.db import models
from django.contrib.auth.models import User, AnonymousUser

# Create your models here.
class Seed(models.Model):
     user = models.ForeignKey(User)
     seed_type = models.CharField(max_length=150, blank=True)
     crop_type = models.CharField(max_length=150, blank=True)
     seed_variety = models.CharField(max_length=150, blank=True)
     seed_description = models.TextField(blank=True)
     enough_to_share = models.BooleanField(default=False)
     year = models.CharField(max_length=150, blank=True)
     origin = models.CharField(max_length=150, blank=True)

     archived = models.BooleanField(default=False, blank=False)

     def __unicode__(self):
         return self.user.username + "\'s " + self.seed_type 

     def __str__(self):
         return self.user.username + "\'s " + self.seed_type 


class Event(models.Model):
	name = models.CharField(max_length=150, blank=True)
	date = models.DateField()
	show_on_seed_edit = models.BooleanField(default=True)
	seed = models.ManyToManyField(Seed, blank=True, null=True)
	description = models.TextField(blank=True)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

seednetwork/models.py
from django.db import models
from django.contrib.auth.models import User, AnonymousUser

# Create your models here.

class MemberInfo(models.Model):
	user = models.ForeignKey(User)
	email_is_public = models.BooleanField(default=True)

	town = models.CharField(max_length=150, blank=True)

	phone = models.CharField(max_length=150, blank=True)
	phone_is_public = models.BooleanField(default=True)

	street_address = models.TextField(blank=True)
	street_address_is_public = models.BooleanField(default=True)

	mailing_address = models.TextField(blank=True)
	mailing_address_is_public = models.BooleanField(default=True)

	about_me = models.TextField(blank=True)
	include_in_member_profiles = models.BooleanField(default=True)

	def __unicode__(self):
		return self.user.first_name + ' ' + self.user.last_name

	def __str__(self):
		return self.user.first_name + ' ' + self.user.last_name

seedlibrary/forms.py
from django import forms
from seednetwork.forms import SeedNetworkBaseForm
from seedlibrary.models import Event

class SeedForm(SeedNetworkBaseForm):
	seed_type = forms.CharField(max_length=150, required=False, help_text="i.e. vegetable, herb, perennial, fruit bush, fruit tree, etc.")
	crop_type = forms.CharField(max_length=150, required=False, help_text="i.e. carrot, bean, mint, day lillies, currant, apple, etc.")
	seed_variety = forms.CharField(max_length=150, required=False, help_text="i.e. Danvers, KY Wonder, Peppermint, etc.")
	seed_description = forms.CharField(widget=forms.Textarea(attrs={'rows':'5', 'cols':'60'}), required=False, help_text="How has it performed? Days to maturity? What traits? etc.")
	enough_to_share = forms.BooleanField(required=False, help_text="Do you have enough to share?")
	year = forms.CharField(max_length=150, required=False)
	origin = forms.CharField(max_length=150, required=False, help_text="Where did you first obtain the seed?")
	events = forms.ModelMultipleChoiceField(Event.objects.filter(show_on_seed_edit=True), required=False, widget=forms.CheckboxSelectMultiple, help_text="What events will you bring the seed to?")

class SeedExportForm(SeedNetworkBaseForm):
	archive = forms.BooleanField(required=False, help_text="Do you want to export your archived seed listings?")

seedlibrary/views.py
# Seed library views
from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.template.context import RequestContext
from django.contrib.auth.decorators import login_required

from seedlibrary.forms import SeedForm, SeedExportForm
from seedlibrary.models import Seed, Event

from datetime import datetime, timedelta

# For rendering seed lists in CSV format
import csv
from django.http import HttpResponse

def home(request):
	return render_to_response('seedlib-home.html',
		{},
		context_instance=RequestContext(request))

def update_seed_events(seed, all_checked_events):
	all_events = Event.objects.filter(show_on_seed_edit=True)
	for e in all_events:
		if e in all_checked_events:
			e.seed.add(seed)
		else:
			e.seed.remove(seed)

@login_required
def seed_create(request):
	seed_form = SeedForm()  
	if request.method == 'POST':
		seed_form = SeedForm(request.POST)
		if seed_form.is_valid():

			seed = Seed.objects.create(
				user = request.user,
				seed_type = seed_form.cleaned_data['seed_type'],
				crop_type = seed_form.cleaned_data['crop_type'],
				seed_variety = seed_form.cleaned_data['seed_variety'],
				seed_description = seed_form.cleaned_data['seed_description'],
				enough_to_share = seed_form.cleaned_data['enough_to_share'],
				year = seed_form.cleaned_data['year'],
				origin = seed_form.cleaned_data['origin']
			)
			seed.save()

			update_seed_events(seed, seed_form.cleaned_data['events'])

			return redirect('seedlibrary.views.seed_create_confirm')
		

	return render_to_response('seed-create.html',
		{"seed_form":seed_form},
		context_instance=RequestContext(request))
	


@login_required
def seed_create_confirm(request):
	return render_to_response('seed-confirm.html',
		{},
		context_instance=RequestContext(request))

        
@login_required
def seeds(request):  
	seed_list = Seed.objects.filter(user=request.user, archived=False)
	seed_archive_list = Seed.objects.filter(user=request.user, archived=True)

	return render_to_response('seeds.html',
		{ "seed_list": seed_list, "seed_archive_list": seed_archive_list },
		context_instance=RequestContext(request))

def fill_seed_from_form(seed, form):
	seed.seed_type = form.cleaned_data['seed_type']
	seed.crop_type = form.cleaned_data['crop_type']
	seed.seed_variety = form.cleaned_data['seed_variety']
	seed.seed_description = form.cleaned_data['seed_description']
	seed.enough_to_share = form.cleaned_data['enough_to_share']
	seed.year = form.cleaned_data['year']
	seed.origin = form.cleaned_data['origin']

@login_required
def seed_export(request):
	seed_export_form = SeedExportForm()
	if request.method == 'POST':
		seed_export_form = SeedExportForm(request.POST)
		if seed_export_form.is_valid():
			try:
				request.POST['archive']
			except:
				include_archived = False
			else:
				include_archived = True
			seed_list = Seed.objects.filter(user=request.user, archived=include_archived)
			return seeds_as_csv_to_response(seed_list)

	return render_to_response('seed-export.html',
			{"seed_export_form":seed_export_form},
			context_instance=RequestContext(request))

def seeds_as_csv_to_response(seed_list):
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="Seeds.csv"'
	writer = csv.writer(response)
	# Write header row.
	writer.writerow([
		'Title',
		'Type',
		'Quantity',
		'Common Name',
		'Unit label',
		'Seed Expiration Date',
		'Exchange Expiration Date',
		'Notes',
		'Scientific Name'
		])
	for seed in seed_list:
		title = ' '.join(seed.seed_description.split(' ')[:10])
		type = 'Give' if seed.enough_to_share else 'Get'
		quantity = ''
		common_name = seed.crop_type
		unit = 'Packets'
		seed_expiry_date = ''
		exchange_expiry_date = datetime.now() + timedelta(days=365)
		notes = seed.seed_description
		scientific_name = seed.seed_variety
		writer.writerow([
			title,
			type,
			quantity,
			common_name,
			unit,
			seed_expiry_date,
			exchange_expiry_date.isoformat(),
			notes,
			scientific_name
			])

	return response

@login_required
def seed_edit(request, id):
	seed = get_object_or_404(Seed, pk=id)
	error = None

	if request.method == 'POST':
		form = SeedForm(request.POST)
		if form.is_valid():
			fill_seed_from_form(seed, form)
			seed.save()

			update_seed_events(seed, form.cleaned_data['events'])

			return redirect('seedlibrary.views.seeds')
	else:
		data = {}
		data['seed_type'] = seed.seed_type
		data['crop_type'] = seed.crop_type
		data['seed_variety'] = seed.seed_variety
		data['seed_description'] = seed.seed_description
		data['enough_to_share'] = seed.enough_to_share
		data['year'] = seed.year
		data['origin'] = seed.origin
		e_ids = []
		for e in seed.event_set.all():
			e_ids.append(e.id)
		data['events'] = e_ids

		form = SeedForm(data)

	return render_to_response('seed-edit.html',
		{ "seed":seed, "form": form, "error": error },
        context_instance=RequestContext(request))

@login_required
def seed_confirm_archive(request, id):
	seed = get_object_or_404(Seed, pk=id, user=request.user)
	error = None

	if request.method == 'POST':
		if request.POST['command'] == 'archive' and not seed.archived:
			seed.archived = True
			seed.save()
		elif request.POST['command'] == 'unarchive' and seed.archived:
			seed.archived = False
			seed.save()

		return redirect('seedlibrary.views.seeds')

	return render_to_response('seed-confirm-archive.html',
			{ "seed":seed, "error": error },
			context_instance=RequestContext(request))

@login_required
def events(request):
	yesterday = datetime.now() - timedelta(days=1)
	event_list = Event.objects.filter(date__gte=yesterday).order_by('date')
	past_event_list = Event.objects.filter(date__lt=yesterday).order_by('-date')

	return render_to_response('events.html',
			{ "event_list": event_list, "past_event_list":past_event_list},
            context_instance=RequestContext(request))

@login_required
def seeds_at_event(request, id):
	event = get_object_or_404(Event, pk=id)

	seed_list = event.seed.all()

	return render_to_response('seeds-at-event.html',
			{ "seed_list": seed_list, "event": event },
			                  context_instance=RequestContext(request))

seedlibrary/templates/events.html
{% extends "base.html" %}
{% block title %}Seed bank: Events{% endblock %}
{% block pagetitle %}Events{% endblock %}
{% block content %}
    {% if event_list %}
        {% for event in event_list %}
            <ul>
            <li><a href="{% url 'seedlibrary.views.seeds_at_event' id=event.id %}">{{ event.name }}</a> on {{ event.date|date }}
            <p>{{ event.description }}</p>
            </li>
            </ul>
        {% endfor %}
    {% else %}
        There are no events
    {% endif %}
    <h2>Past Events</h2>
    {% if past_event_list %}
        {% for event in past_event_list %}
            <ul>
                <li><a href="{% url 'seedlibrary.views.seeds_at_event' id=event.id %}">{{ event.name }}</a> on {{ event.date|date }}
                    <p>{{ event.description }}</p>
                </li>
            </ul>
        {% endfor %}
    {% else %}
        There are no past events
    {% endif %}

{% endblock %}

seedlibrary/templates/home.html
{% extends "base.html" %}
{% block title %}Seed Library: Home{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {{ user.username }}
    {% else %}
        <h3>Login</h3>
        <form id="loginform" action="/login/" method="post">{% csrf_token %}
            <p><strong>Username</strong><br/><input type="text" name="username" /><br/>
                <strong>Password</strong><br/><input type="password" name="password" /><br/>
                <input type="submit" name="login" value="login" /><br/>
            </p>
        </form>
    {% endif %}
{%endblock%}

seedlibrary/templates/inc-seed-table.html
<table class="results">
    <tr><th>Type</th>
        <th>Crop</th>
        <th>Variety</th>
        <th>Year</th>
        <th>Origin</th>
        <th>Share</th>
        <th>Description</th>
        {% if full %}
        <th>Member</th>
        <th>Town</th>
        {% endif %}
        <th>Actions</th></tr>
    {% for seed in seed_list %}
        <tr>
            <td>{{ seed.seed_type }}</td>
            <td>{{ seed.crop_type }}</td>
            <td>{{ seed.seed_variety }}</td>
            <td>{{ seed.year }}</td>
            <td>{{ seed.origin }}</td>
            <td>{{ seed.enough_to_share|yesno:"Yes,No" }}</td>
            <td>{{ seed.seed_description }} </td>

            {% if full %}
            {% with seed.user.memberinfo_set.all|first as mi %}
                <td>
                    {% if mi.include_in_member_profiles %}
                        <a href="{% url 'seednetwork.views_user.member' mid=mi.id %}">{{ seed.user.username }}</a>
                    {% else %}
                        {{ seed.user.username }}
                    {% endif %}
                </td>
                <td>{{ mi.town }}</td>
            {% endwith %}
            {% endif %}
            <td>
                {% ifequal seed.user.username user.username %}
                    <a href="{% url 'seedlibrary.views.seed_edit' id=seed.id %}">Edit</a>
                    {% if seed.archived %}
                        | <a href="{% url 'seedlibrary.views.seed_confirm_archive' id=seed.id %}">Unarchive</a>
                    {% else %}
                        | <a href="{% url 'seedlibrary.views.seed_confirm_archive' id=seed.id %}">Archive</a>
                    {% endif %}
                {% endifequal %}

            </td>
        </tr>
    {% endfor %}
</table>

seedlibrary/templates/seed-confirm-archive.html
{% extends "base.html" %}
{% block title %}Seed Bank: Confirm seed {% if seed.archived %}un{% endif %}archive{% endblock %}
{% block pagetitle %}{% if seed.archived %}Unarchive{% else %}Archive{% endif %} this seed?{% endblock %}
{% block content %}
    <p><form method="post" action="{% url 'seedlibrary.views.seed_confirm_archive' id=seed.id %}">
        {% csrf_token %}
        Are you sure you want to {% if seed.archived %}un{% endif %}archive this seed?
    </p>
    <table class="form">
        <tr><th>Type:</th><td>{{ seed.seed_type }}</td></tr>
        <tr><th>Crop:</th><td>{{ seed.crop_type }}</td></tr>
        <tr><th>Variety:</th><td>{{ seed.seed_variety }}</td></tr>
    </table>
    <p><br/><a href="{% url 'seedlibrary.views.seeds' %}">Cancel</a> |
        {% if seed.archived %}
            <input type="hidden" name="command" value="unarchive">
            <input type="submit" value="Unarchive" />
        {% else %}
            <input type="submit" value="Archive" />
            <input type="hidden" name="command" value="archive">
        {% endif %}
    </p>
    </form>
{%endblock%}

seedlibrary/templates/seed-confirm.html
{% extends "base.html" %}
{% block title %}Seed Bank: Seed Listed Successfully{% endblock %}
{% block pagetitle %}Seed Listed Successfully{% endblock %}
{% block content %}
		<p>Your seed has been listed. Thanks!</p>
		<p><a href="{% url 'seedlibrary.views.seed_create' %}">List Another</a>
		<p><a href="{% url 'seedlibrary.views.seeds' %}">Go back to the Library</a>
{%endblock%}

seedlibrary/templates/seed-create.html
{% extends "base.html" %}
{% block title %}Seed Bank: List a New Seed {% endblock %}
{% block pagetitle %}List a New seed{% endblock %}

{% block content %}
   
        <h3>List your seed! (one variety per form, please)</h3>
        <form action="." method="post">{% csrf_token %}
            <table>
			{{  seed_form.as_table }}
			</table>
                <input type="submit"  value="Submit Seed" />
            
        </form>
    
{%endblock%}

seedlibrary/templates/seed-edit.html
{% extends "base.html" %}
{% block title %}Seed Bank: Edit Seed {% endblock %}
{% block pagetitle %}Edit Seed{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <form method="post" action="{% url 'seedlibrary.views.seed_edit' id=seed.id %}">{% csrf_token %}
        <table>
        {{ form.as_table }}
            <tr><td colspan="2"><a href="{% url 'seedlibrary.views.seeds' %}">Cancel</a> |
			<input type="submit" value="Update" /></td></tr>
        </table>
        </form>
    {% else %}
    {% endif %}
{% endblock %}

seedlibrary/templates/seed-export.html
{% extends "base.html" %}
{% block title %}Seed Bank: Export Seeds {% endblock %}
{% block pagetitle %}Export Seeds{% endblock %}

{% block content %}

        <h3>Export your seeds</h3>
        <form action="." method="post">{% csrf_token %}
            <table>
                {{  seed_export_form.as_table }}
            </table>
            <input type="submit"  value="Export Seeds" />

        </form>

{%endblock%}

seedlibrary/templates/seed-search.html
{% extends "base.html" %}
{% block title %}Seed Bank: Search{% endblock %}
{% block pagetitle %}Search{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <form  class="searchform" method="post" action="{% url 'seedlibrary.views_search.seed_search' %}">{% csrf_token %}
            <input type="text" name="q" value="{{ q }}"> <input type="submit" value="Search"><br/>
            <input type="checkbox" name="archive" {{ archived_checked }}>Include archived seeds
        </form>
        <br/>
        {% if seed_list %}
            {% with seed_list_for_table=seed_list full=True  %}
                {% include 'inc-seed-table.html' %}
            {% endwith %}
        {% else %}
            <p>No seeds matched your search.</p>
        {% endif %}

    {% endif %}
{%endblock%}

seedlibrary/templates/seedlib-home.html
{% extends "base.html" %}
{% block title %}Seed Bank: Home{% endblock %}
{% block pagetitle %}Seed Bank Home{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        {{ user.username }}
    {% else %}
        <h3>Login</h3>
        <form id="loginform" action="/login/" method="post">{% csrf_token %}
            <p><strong>Username</strong><br/><input type="text" name="username" /><br/>
                <strong>Password</strong><br/><input type="password" name="password" /><br/>
                <input type="submit" name="login" value="login" /><br/>
            </p>
        </form>
    {% endif %}
{%endblock%}

seedlibrary/templates/seeds-at-event.html
{% extends "base.html" %}
{% block title %}Seeds at {{ event.name }}{% endblock %}
{% block pagetitle %}Seeds at {{ event.name }}{% endblock %}
{% block content %}
    <p>Date: {{ event.date }}</p>
    <p>{{ event.description }}</p>
    {% if seed_list %}
        {% with seed_list_for_table=seed_list full=True %}
            {% include 'inc-seed-table.html' %}
        {% endwith %}
    {% else %}
    <p>No seeds at this event.</p>
    {% endif %}
{% endblock %}

seedlibrary/templates/seeds.html
{% extends "base.html" %}
{% block title %}Seed bank: {{ user.username}}'s Seeds{% endblock %}
{% block pagetitle %}{{ user.username}}'s Seeds{% endblock %}
{% block content %}
<p>
    <a href="{% url 'seedlibrary.views.seed_create' %}">List another seed</a>
    |
    <a href="{% url 'seedlibrary.views.seed_export' %}">Export my seeds</a>
</p>
    <h2>Active</h2>
<p>You have listed {{ seed_list.count }} seed{{ seed_list.count|pluralize }}.</p>
{% if seed_list %}
    {% with seed_list_for_table=seed_list full=False %}
    {% include 'inc-seed-table.html' %}
    {% endwith %}
{% endif %}
{% if seed_archive_list %}
    <h2>Archive</h2>
    {% with seed_list_for_table=seed_archive_list full=False %}
        {% include 'inc-seed-table.html' %}
    {% endwith %}
{% endif %}
{% endblock %}